# Generated by Django 5.2.7 on 2025-10-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_added'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'per kilogram'), ('g', 'per gram'), ('bunch', 'per bunch'), ('pack', 'per pack'), ('piece', 'per piece'), ('ml', 'per millilitre'), ('litre', 'per litre'), ('dozen', 'per dozen'), ('crate', 'per crate'), ('packet', 'per packet')], default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('plant', 'Plant-based'), ('animal', 'Animal-based')], default='plant', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter price in Kenyan Shillings (KES)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available stock in kilograms, pieces, litres, etc.'),
        ),
    ]
