# Generated by Django 5.2.7 on 2025-10-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_product_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('field_crops', 'Field Crops'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('herbs_spices', 'Herbs & Spices'), ('dairy', 'Dairy Products'), ('eggs', 'Eggs'), ('meat', 'Meat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available stock quantity (kg, pieces, litres, etc.)'),
        ),
    ]
